
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 10 09:33:40 AST 2014
//----------------------------------------------------

package edu.icom4029.cool.parser;

/** CUP generated interface containing symbol constants. */
public interface TokenConstants {
  /* terminals */
  public static final int MULT = 31;
  public static final int INHERITS = 7;
  public static final int POOL = 11;
  public static final int CASE = 14;
  public static final int LPAREN = 23;
  public static final int SEMI = 28;
  public static final int MINUS = 30;
  public static final int STR_CONST = 43;
  public static final int RPAREN = 24;
  public static final int NOT = 18;
  public static final int AND = 19;
  public static final int TYPEID = 41;
  public static final int LT = 34;
  public static final int IN = 6;
  public static final int OR = 20;
  public static final int COMMA = 36;
  public static final int CLASS = 2;
  public static final int FI = 4;
  public static final int DIV = 32;
  public static final int LOOP = 10;
  public static final int PLUS = 29;
  public static final int ASSIGN = 21;
  public static final int IF = 5;
  public static final int DOT = 37;
  public static final int LE = 35;
  public static final int OF = 17;
  public static final int EOF = 0;
  public static final int INT_CONST = 42;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int ISVOID = 8;
  public static final int EQ = 33;
  public static final int ERROR = 45;
  public static final int COLON = 27;
  public static final int NEG = 39;
  public static final int LBRACE = 25;
  public static final int ELSE = 3;
  public static final int DARROW = 22;
  public static final int WHILE = 13;
  public static final int ESAC = 15;
  public static final int LET = 9;
  public static final int THEN = 12;
  public static final int RBRACE = 26;
  public static final int BOOL_CONST = 44;
  public static final int OBJECTID = 40;
  public static final int AT = 38;
}

